### ISSUE TITLE
add text - coming soon!

### ISSUE THREAD

**Issue by JacquelineMorck** [UnionDesign/keyin#3]
<img width="1097" alt="screen shot 2016-06-01 at 11 24 13 am" src="https://cloud.githubusercontent.com/assets/18389551/15720908/69c669ac-27eb-11e6-8787-050556c92b01.png">

<img width="1014" alt="screen shot 2016-06-01 at 11 26 21 am" src="https://cloud.githubusercontent.com/assets/18389551/15720998/e07bf44a-27eb-11e6-82d4-8f8eb939ea2f.png">

add coming soon next to industry (or under icon however it looks best) - **on all areas** 
[icon] Veterinary (coming soon!)
[icon] Plastic Surgery (coming soon!)

**Comment by JacquelineMorck** [comment]
swap health IT and Building Materials in all areas:

order:
medsim
BM
health IT

**Comment by UnionDesign** [comment]
- These are just pulling in the page names so you could just rename those pages if that works
- Order can be changed in admin by drag and drop

**Comment by JacquelineMorck** [comment]
great i'll do that now
