### ISSUE TITLE
footer - widen text box

### ISSUE THREAD

**Issue by JacquelineMorck** [UnionDesign/keyin#4]
contact us shouldn't drop down - widen margin so it is on one line please
<img width="344" alt="screen shot 2016-06-01 at 11 25 17 am" src="https://cloud.githubusercontent.com/assets/18389551/15720949/9aae36f8-27eb-11e6-8245-f0e17ab303d0.png">

**Comment by UnionDesign** [comment]
Odd it's not doing this for me at any screen size. They actually already have a ton of space to grow into. Maybe it's the way your browser is interpreting it. In any case I added a "no wrap" style to those links should never break onto two line.

**Comment by JacquelineMorck** [comment]
thanks!
